env variable is added to auth
Avdhesh-Varshney/Chanakya-Niti pull request #120
Opened 2024-06-14 10:47 UTC by Sushanth-Hebri

Auth key is added with env variable

2024-06-14 10:50 UTC, Sushanth-Hebri commented
Environment variable used "REACT_APP_API_KEY" ,
add .env file to .gitignore

2024-06-15 03:57 UTC, Avdhesh-Varshney requested changes

2024-06-15 03:57 UTC, Avdhesh-Varshney commented on .env
@Sushanth-Hebri still this key will be visible. So, you have to delete this file. I will add this key in deployement env variables. and resolve the conflicts.

2024-06-15 03:57 UTC, Avdhesh-Varshney commented on src/components/Quotes/QuotesSection.jsx
> +          'Authorization': process.env.REACT_APP_API_KEY
named it `QUOTES_API_KEY`

2024-06-15 06:45 UTC, closed without merging

2024-06-15 07:11 UTC, Sushanth-Hebri commented
solved this in #124 , auth key must start with REACT_APP for safety , for custom key there need to be separate wired config ,
now auth key is REACT_APP_QUOTES_API_KEY