FIX:[#58] - (2)
Avdhesh-Varshney/chanakya-niti pull request #125
Opened 2024-06-15 07:51 UTC by Madhavdua

Closes: 

- **Title** : UI improvements
- **Name:** Madhav
- SSOC contributor

Give a clear description of what have you added or modifications made
**I have made the below changes with the required bg wave animation and file formatting.**
I have improved UI, Restructured some elements i.e instead of having complete code in one file, seperate components like searchbar.jsx etc.
Fixed negative episode search

### Type of change ☑️

- [ x] Bug fix : **Episode will be searched only for positive value**
- [ x] New feature : **updated UI**
- [ x] Code style update: Restructured some elements i.e instead of having complete code in one file, seperate components like searchbar.jsx etc.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x ] My changes generate no new warnings.

### Screenshots 📷
![Screenshot 2024-06-15 131849](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/67e5e8c0-bf8a-4a48-a816-de0be407dc9f)
![Screenshot 2024-06-15 131913](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/3ee39404-e486-4c1c-9fc3-dba7306fc0bc)

### Note to reviewers 📄
Instead of passing of props, using context Api should be used.
For which, should i raise an issue for it?

2024-06-16 04:22 UTC, Avdhesh-Varshney requested changes
@Madhavdua i think you have not updating your forked repo. That's why there are alots of conflicts in this pr, either resolve them or re-raise your pr after updating your repo.

This makes hard to review the pr.

2024-06-16 13:00 UTC, Madhavdua commented
I have carefully resolved all conflicts. Kindly preview them.

2024-06-16 17:43 UTC, Avdhesh-Varshney requested changes
@Madhavdua still there are some files where double quotes is un-necessarly updated by single quotes.

2024-06-16 17:43 UTC, Avdhesh-Varshney commented on src/components/Alert/Alert.jsx
un-necessary change, remove this new created line

2024-06-16 17:45 UTC, Avdhesh-Varshney commented on src/components/Alert/Alert.jsx
work on the ui as it's not good ux.

![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/114330097/59043b67-9200-481a-8561-0bfa49365414)

2024-06-16 19:04 UTC, Madhavdua commented on src/components/Alert/Alert.jsx
> work on the ui as it's not good ux.
> 
> ![image](https://private-user-images.githubusercontent.com/114330097/340123110-59043b67-9200-481a-8561-0bfa49365414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjQ4MDksIm5iZiI6MTcxODU2NDUwOSwicGF0aCI6Ii8xMTQzMzAwOTcvMzQwMTIzMTEwLTU5MDQzYjY3LTkyMDAtNDgxYS04NTYxLTBiZmE0OTM2NTQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxOTAxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzI3Y2I2ZmRmYjllMWM2ZDhlYmY2ZjdiYTdjYzI3NmYwMjY5MGNjOTk3ZmNjNmJjNWEwYjIxMDI2NjNjZGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n_Y8CxYe83zmevR2F4P-eg6yaIXx2dKM5s_pxpEIoX8)

Sir, i don't know why you are getting this UI, i have attached SS of UI i made.Kindly help me understand the issue.
![Screenshot 2024-06-15 131849](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/9eb3e52b-6984-4a39-aa4f-616aa5d3bf76)
![Screenshot 2024-06-17 003351](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/48ef99ca-1b23-4c93-881c-e3ecdfec1b0c)

2024-06-18 06:48 UTC, Madhavdua commented
Kindly update me sir.

2024-06-19 07:58 UTC, Avdhesh-Varshney commented
@Madhavdua now it's looks nice. [link](https://chanakya-git-fork-madhavdua-ui-ba42ee-avdheshvarshneys-projects.vercel.app/). But this will remove the contribution of others from the website like quotes generation and many more things.

2024-06-19 11:01 UTC, Madhavdua commented
I understand.
The quote section is still present in code and i will display it properly in future updates.
The other major difference is the input (Search box), which i'll be working on to integrate and will soon update the branch.
Kindly tell me any futher requirements (if any).

2024-06-19 12:13 UTC, Avdhesh-Varshney commented
> Thank you for submitting your pull request! We'll review it as soon as possible. For further communication, join our discord server https://discord.gg/tSqtvHUJzE.

@Madhavdua have you joined this server? Because due to my inactivity, this project is moving in a loooop. So, join it to get notify with the project upcoming changes and guidelines.

2024-06-19 17:02 UTC, Madhavdua commented
Hey @Avdhesh-Varshney i have integrated new feature and the quote section is not displayed yet, it may be added in future updates. 
For now, it is the final update, **it can be merged safely**, once previewed.
![Screenshot 2024-06-19 222221](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/94641232/bd8bb0bb-baaa-4492-a175-5295921b2324)
![Screenshot 2024-06-19 222259](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/94641232/c1eeb82f-33c4-4c94-a6a4-6526d4bb8817)

2024-06-21 03:55 UTC, Avdhesh-Varshney commented
@Madhavdua leave it. Start working on other new issues and move with the flow of project.

2024-06-21 03:55 UTC, closed without merging