Added favicon
Avdhesh-Varshney/chanakya-niti pull request #235
Opened 2024-07-12 17:16 UTC by Maana-Ajmera

Closes #228 
- **Title** : Favicon
- **Name:** : Maana Ajmera
- **Idenitfy yourself:** GSSOC

### Describe the add-ons or changes you've made 📃
I have added the favicon to the website which adds a good look to it

### Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/02496332-bef6-474a-8735-340ce16398a6)

2024-07-14 05:35 UTC, Avdhesh-Varshney requested changes

2024-07-14 05:35 UTC, Avdhesh-Varshney commented on favicon.png
convert it into ico format

2024-07-14 05:36 UTC, Avdhesh-Varshney commented on favicon.png
And keep this image in circular cropping

2024-07-14 18:17 UTC, Maana-Ajmera commented
![image](https://github.com/user-attachments/assets/c45bb598-a3e7-4815-81a7-da322c070576)

@Avdhesh-Varshney done

2024-07-16 11:29 UTC, Maana-Ajmera commented
@Avdhesh-Varshney I have resolved conflicts and done the changes , please review my PR and if there is anything else that needs to be changes , please let me know

2024-07-16 14:38 UTC, Avdhesh-Varshney commented
@Maana-Ajmera it is resolved.

2024-07-16 14:38 UTC, closed without merging