Feat:  groq API integration
Avdhesh-Varshney/chanakya-niti pull request #242
Opened 2024-07-17 14:51 UTC by PranotiPD

Closes:  #240

- **Title** : groq API integration
- **Name:**  Pranoti Durugkar
- **Idenitfy yourself:**  Gssoc

### Describe the add-ons or changes you've made 📃

I have added a page under the resources section where user can put their question and search for answers and user will be answered as if it is being answered by Chanakya.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

### Note to reviewers 📄

2024-07-18 03:15 UTC, Avdhesh-Varshney requested changes
@PranotiPD LGTM.

2024-07-18 03:15 UTC, Avdhesh-Varshney commented on src/components/shared/Footer.jsx
> +            <li><NavLink to="/resources/audio" className="text-decoration-none text-dark"><FaMusic className="me-2" /> ChanakyaGpt</NavLink></li>
![image](https://github.com/user-attachments/assets/9d25f00f-5691-422a-b1c4-7dd3ed4cdd83)

fix routing

2024-07-18 03:15 UTC, Avdhesh-Varshney commented on src/components/shared/Navbar.jsx
> +                <li><Link className="dropdown-item" to="/resources/chanakyaGpt">ChanakyaGpt</Link></li>
![image](https://github.com/user-attachments/assets/1ff0ddd2-a3c1-40df-929c-da76ec0be949)

fix routing

2024-07-18 03:16 UTC, Avdhesh-Varshney commented
Always link your issue not the pr. Update it.

2024-07-18 16:56 UTC, PranotiPD commented
@Avdhesh-Varshney made routing changes

2024-07-21 04:23 UTC, Avdhesh-Varshney approved these changes

2024-07-21 04:24 UTC, merged