Converted_Images_to_WebP_for_Better_Optimization
Avdhesh-Varshney/chanakya-niti pull request #312
Opened 2024-10-20 09:46 UTC by smog-root

**Fixes** #309 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels! I think this PR deserves level3 label. Please add it i have worked hard to do this! 

@Avdhesh-Varshney

2024-10-21 12:41 UTC, smog-root commented
Add labels and assign me! then merge !

2024-10-21 13:02 UTC, Avdhesh-Varshney requested changes
Don't covert logo icon from png to webp. Just convert only high resolution images.
- Review your deployment on your own

2024-10-21 13:02 UTC, Avdhesh-Varshney commented on public/arthashastra.webp
.

2024-10-21 13:02 UTC, Avdhesh-Varshney commented on public/favicon.ico
.

2024-10-21 13:02 UTC, Avdhesh-Varshney commented on public/image.webp
.

2024-10-21 13:05 UTC, smog-root commented
Okay I will convert back logo form webp back to png! @Avdhesh-Varshney

2024-10-23 16:10 UTC, smog-root commented
@Avdhesh-Varshney merge it!!!

2024-10-26 16:58 UTC, smog-root commented
@Avdhesh-Varshney ??

2024-10-28 15:07 UTC, Avdhesh-Varshney requested changes
These all are icons not the images

2024-10-28 15:07 UTC, Avdhesh-Varshney commented on public/android-chrome-192x192.png
.

2024-10-28 15:07 UTC, Avdhesh-Varshney commented on public/android-chrome-512x512.png
.

2024-10-28 15:07 UTC, Avdhesh-Varshney commented on public/apple-touch-icon.png
.

2024-10-28 15:07 UTC, Avdhesh-Varshney commented on public/favicon-16x16.png
.

2024-10-28 15:07 UTC, Avdhesh-Varshney commented on public/favicon-32x32.png
.

2024-10-28 15:08 UTC, closed without merging

2024-10-28 15:09 UTC, smog-root commented
@Avdhesh-Varshney I will open another PR with changes!!!