https://github.com/Avdhesh-Varshney/Chanakya-Niti/issues/36
Avdhesh-Varshney/Chanakya-Niti pull request #99
Opened 2024-06-08 09:00 UTC by kapilG0

Closes: #36 
- **Title** : Contributor
- **Name:** Kapil Gupta
- **Idenitfy yourself:** SSOC,GSSOC

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

### Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/59639410/9dac8fa9-89f0-4dca-b51f-21debd1aae41)

### Note to reviewers 📄

2024-06-08 17:47 UTC, Avdhesh-Varshney requested changes
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/114330097/f8e715f0-5eed-419e-962e-a081a10299e4)
Still shows same issue.

2024-06-09 03:03 UTC, kapilG0 commented
> ![image](https://private-user-images.githubusercontent.com/114330097/337922573-f8e715f0-5eed-419e-962e-a081a10299e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDI0NzIsIm5iZiI6MTcxNzkwMjE3MiwicGF0aCI6Ii8xMTQzMzAwOTcvMzM3OTIyNTczLWY4ZTcxNWYwLTVlZWQtNDE5ZS05NjJlLWEwODFhMTAyOTllNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMzAyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGJlNzU5OWEyYmE1NTVlMDM5NGVjYjFmZjc4NmE0NzM3Nzg4NGE5MmU2YzUwODdiZDA4NGVhYThkNDc0MTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LCXHO6ng3vhT_RdDfS_8XXgkkhEnj7TMCUSFgLhQG50) Still shows same issue.

Ok let me check again

2024-06-09 06:10 UTC, kapilG0 commented
> > ![image](https://private-user-images.githubusercontent.com/114330097/337922573-f8e715f0-5eed-419e-962e-a081a10299e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDI0NzIsIm5iZiI6MTcxNzkwMjE3MiwicGF0aCI6Ii8xMTQzMzAwOTcvMzM3OTIyNTczLWY4ZTcxNWYwLTVlZWQtNDE5ZS05NjJlLWEwODFhMTAyOTllNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMzAyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGJlNzU5OWEyYmE1NTVlMDM5NGVjYjFmZjc4NmE0NzM3Nzg4NGE5MmU2YzUwODdiZDA4NGVhYThkNDc0MTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LCXHO6ng3vhT_RdDfS_8XXgkkhEnj7TMCUSFgLhQG50) Still shows same issue.
> 
> Ok let me check again

Hello @Avdhesh-Varshney  please check now i have fixed that and commit my code again in same pr

2024-06-09 17:50 UTC, Avdhesh-Varshney requested changes
@kapilG0 try to solve it with the presence of timeout operation.
And the change the title of the pr same as issue

2024-06-09 17:50 UTC, Avdhesh-Varshney commented on src/App.jsx
> +    // setTimeout(() => {
don't remove this timeout.

2024-06-10 02:49 UTC, kapilG0 commented
> @kapilG0 try to solve it with the presence of timeout operation. And the change the title of the pr same as issue

Hello @Avdhesh-Varshney thank you for your response i have added that and update header

2024-06-11 04:30 UTC, Avdhesh-Varshney approved these changes
@kapilG0 PR Approved 🎉
But for next time, don't do un-necessary changes without discussing.

2024-06-11 04:30 UTC, merged